#!/bin/bash

script_name="cp-tool.py"
script_path=$(command -v "$script_name")

# Run the python script
output=$(python "$script_path" $@)

# Initialize variable to store parsed directory
parsed_dir=""

# Read lines from output string
while IFS= read -r line; do
    if [[ $line == dir=* ]]; then
        parsed_dir=${line#dir=}
        parsed_dir="${parsed_dir}"
        break;
    else
        echo "$line";
    fi
done <<< "$output"

cd "$parsed_dir" || exit 1

